export const campaignLabels: Record<number, string> = {
  0: 'Core',
  1: 'Prophecies',
  2: 'Factions',
  3: 'Nightfall',
  4: 'Eye of the North',
};

export const professionLabels: Record<number, string> = {
  0: 'None',
  1: 'Warrior',
  2: 'Ranger',
  3: 'Monk',
  4: 'Necromancer',
  5: 'Mesmer',
  6: 'Elementalist',
  7: 'Assassin',
  8: 'Ritualist',
  9: 'Paragon',
  10: 'Dervish',
};

export const attributeLabels: Record<number, string> = {
  0: 'Fast Casting',
  1: 'Illusion Magic',
  2: 'Domination Magic',
  3: 'Inspiration Magic',
  4: 'Blood Magic',
  5: 'Death Magic',
  6: 'Soul Reaping',
  7: 'Curses',
  8: 'Air Magic',
  9: 'Earth Magic',
  10: 'Fire Magic',
  11: 'Water Magic',
  12: 'Energy Storage',
  13: 'Healing Prayers',
  14: 'Smiting Prayers',
  15: 'Protection Prayers',
  16: 'Divine Favor',
  17: 'Strength',
  18: 'Axe Mastery',
  19: 'Hammer Mastery',
  20: 'Swordsmanship',
  21: 'None',
  22: 'Tactics',
  23: 'Beast Mastery',
  24: 'Expertise',
  25: 'Wilderness Survival',
  26: 'Marksmanship',
  27: 'Dagger Mastery',
  28: 'Deadly Arts',
  29: 'Shadow Arts',
  30: 'Communing',
  31: 'Restoration Magic',
  32: 'Channeling Magic',
  33: 'Spawning Power',
  34: 'Leadership',
  35: 'Spear Mastery',
  36: 'Command',
  37: 'Motivation',
  38: 'Scythe Mastery',
  39: 'Wind Prayers',
  40: 'Earth Prayers',
  41: 'Mysticism',
};

export const typeLabels: Record<number, string> = {
  0: 'Skill',
  1: 'Bounty',
  2: 'Hex',
  3: 'Enchantment',
  4: 'Stance',
  5: 'Shout',
  6: 'Signet',
  7: 'Trap',
  8: 'Spirit',
  9: 'Spell',
  10: 'Attack',
  11: 'Pet Attack',
  12: 'Preparation',
  13: 'Glyph',
  14: 'Well',
  15: 'Ward',
  16: 'Form',
  17: 'Echo',
  18: 'Chant',
  19: 'Refrain',
  20: 'Weapon Spell',
  21: 'Ritual',
  22: 'Nature Ritual',
  23: 'Binding Ritual',
  24: 'Hex Spell',
  25: 'Enchantment Spell',
  26: 'Condition',
  27: 'Item Spell',
};