export const campaignLabels: Record<number, string> = {
  0: 'Core',
  1: 'Prophecies',
  2: 'Factions',
  3: 'Nightfall',
  4: 'Eye of the North',
};

export const professionLabels: Record<number, string> = {
  0: 'None',
  1: 'Warrior',
  2: 'Ranger',
  3: 'Monk',
  4: 'Necromancer',
  5: 'Mesmer',
  6: 'Elementalist',
  7: 'Assassin',
  8: 'Ritualist',
  9: 'Paragon',
  10: 'Dervish',
};

export const attributeLabels: Record<number, string> = {
  0: 'Fast Casting',
  1: 'Illusion Magic',
  2: 'Domination Magic',
  3: 'Inspiration Magic',

  4: 'Blood Magic',
  5: 'Death Magic',
  6: 'Soul Reaping',
  7: 'Curses',

  8: 'Air Magic',
  9: 'Earth Magic',
  10: 'Fire Magic',
  11: 'Water Magic',
  12: 'Energy Storage',

  13: 'Healing Prayers',
  14: 'Smiting Prayers',
  15: 'Protection Prayers',
  16: 'Divine Favor',

  17: 'Strength',
  18: 'Axe Mastery',
  19: 'Hammer Mastery',
  20: 'Swordsmanship',

  21: 'Tactics',

  22: 'Beast Mastery',
  23: 'Expertise',
  24: 'Wilderness Survival',
  25: 'Marksmanship',

  26: 'Dagger Mastery',
27: 'Deadly Arts',
28: 'Shadow Arts',
29: 'Critical Strikes',

30: 'Communing',
31: 'Restoration Magic',
32: 'Channeling Magic',
33: 'Spawning Power',

34: 'Leadership',
35: 'Spear Mastery',
36: 'Command',
37: 'Spear Mastery',
38: 'Command',
39: 'Motivation',
40: 'Leadership',

41: 'Scythe Mastery',
42: 'Wind Prayers',
43: 'Earth Prayers',
44: 'Mysticism',

45: 'None',
};

export const typeLabels: Record<number, string> = {
  1: 'Skill',
  2: 'Bow Attack',
  3: 'Melee Attack',
  4: 'Axe Attack',
  5: 'Lead Attack',
  6: 'Off-Hand Attack',
  7: 'Dual Attack',
  8: 'Hammer Attack',
  9: 'Scythe Attack',
  10: 'Sword Attack',
  11: 'Pet Attack',
  12: 'Spear Attack',
  13: 'Chant',
  14: 'Echo',
  15: 'Elite Form',
  16: 'Glyph',
  17: 'Preparation',
  18: 'Binding Ritual',
  19: 'Nature Ritual',
  20: 'Shout',
  21: 'Signet',
  22: 'Spell',
  23: 'Enchantment Spell',
  24: 'Hex Spell',
  25: 'Item Spell',
  26: 'Ward Spell',
  27: 'Weapon Spell',
  28: 'Well Spell',
  29: 'Stance',
  30: 'Trap',
  31: 'Ranged Attack',
  32: 'Ebon Vanguard Ritual',
  33: 'Flash Enchantment Spell',

  38: 'Skill',
  39: 'Spell',
  40: 'Enchantment Spell',
  41: 'Hex Spell',
  42: 'Signet',
};